name: pan-cov-manuscript
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - xarray
  - numpy
  - pandas
  - matplotlib
  - plotnine
  - seaborn
  - jupyter
  - biopython
  - pip
  - pip:
    - venn
